#!/usr/bin/env sh

set -e

DEBUG_MODE=

if [ "$1" = "debug" ]; then
    DEBUG_MODE=debug
fi

cd cl.comercialwindsor.importdataprocess.targetplatform
./plugin-builder $DEBUG_MODE ../cl.comercialwindsor.importdataprocess ../cl.comercialwindsor.importdataprocess.test
